### ISSUE TITLE
Test binaries should be in .gitignore

### ISSUE THREAD

**Issue by ebfull** [scipr-lab/libsnark#16]
`zerocash_pour_ppzksnark/profiling/profile_zerocash_pour_gadget`
and
`zerocash_pour_ppzksnark/tests/test_zerocash_pour_ppzksnark`

**Comment by madars** [comment]
This is a bug in libzerocash, not in libsnark. Would you mind opening it there? Thanks!

**Comment by ebfull** [comment]
whoops had the wrong tab open!
