### ISSUE TITLE
Invalid use of member function size_t libsnark::r1cs_constraint_system<FieldT>::num_variables()

### ISSUE THREAD

**Issue by gargarchit** [scipr-lab/libsnark#173]
**Invalid use of member function size_t libsnark::r1cs_constraint_system<FieldT>::num_variables()**

[Link of the code](https://github.com/scipr-lab/libsnark/blob/c6dab2f2d6a4af31528ee09d6cfe4f6048e2c1b9/libsnark/gadgetlib1/protoboard.tcc#L131)

## Correct Code
```
template<typename FieldT>
void protoboard<FieldT>::dump_variables() const
{
#ifdef DEBUG
    for (size_t i = 0; i < constraint_system.num_variables(); ++i)
    {
        printf("%-40s --> ", constraint_system.variable_annotations[i].c_str());
        values[i].as_bigint().print_hex();
    }
#endif
}
```

**Comment by ValarDragon** [comment]
Thanks for pointing this out! I've merged a fix for this onto staging
