### ISSUE TITLE
Useful demo?

### ISSUE THREAD

**Issue by toodlegoo** [scipr-lab/libsnark#2]
It would be super useful if there were a not-completely-trivial example circuit included.

E.g. the SHA256 compression function with 512+256 bits input and it accepts if the 256 bits matches the hash from the specific 512 bit input.

**Comment by madars** [comment]
libsnark currently includes many non-trivial examples of R1CS constraint systems, not only including SHA256’s compression function but also TinyRAM’s CPU, elliptic-curve pairings, routing networks, and others. We thus think that it is fair to close this issue. We hope that you have fun playing with the examples under gadgetlib1/gadgets/ :-)
