### ISSUE TITLE
BN128 failing same-coefficient checks

### ISSUE THREAD

**Issue by ebfull** [scipr-lab/libsnark#25]
I have a very simple zkSNARK circuit here: https://github.com/ebfull/lightning_circuit

Doing a simple `./get-libsnark && make && ./test` should suffice.

It works just fine and passes my test suite with `ALT_BN128`. However, if you change to `BN128` (in the Makefile) it fails during verification. The proofs appear to generate fine though. (Obviously if the proofs are generated wrong it would explain why they fail same-coefficient checks.)

**Comment by madars** [comment]
Interesting! The core of the problem seems to be independent of the proof system and manifests even in simple BN128 tests, e.g. pairing G1 and G2 generators doesn't yield a generator for the target group.

**Comment by zookozcash** [comment]
Opened a ticket on the ate-pairing repo: https://github.com/herumi/ate-pairing/issues/10

**Comment by herumi** [comment]
I found that Fp12::final_exp() returns different value from libsnark.a.
You can see it as the following.
https://github.com/herumi/libsnark/commit/73c54c78b14ee98e007cfa86bef35cb1b98c6118
```
cd libsnark
make NO_PROCPS=1
make mytest
./ok
./ng
```
`ok` uses my libzm.a directly.
`ng` uses libsnark.a.
`ok` returns correct value 1, but `ng` does not return it.
I checked it at gcc 4.8.4 on Ubuntu 14.04.4 LTS, core i7-4770

I am investigating the reason now.
Could you give me some advice?

**Comment by herumi** [comment]
I'm sorry that the above example is bad. I forgot  -DBN_SUPPORT_SNARK.

**Comment by ebfull** [comment]
`-DBN_SUPPORT_SNARK` fixes it!

**Comment by daira** [comment]
There should be a unit/regression test for this.

**Comment by herumi** [comment]
The latest version of ate-pairing detects that a library made with `SUPPORT_SNARK=1` is used unless `BN_SUPPORT_SNAKE` is defined.
https://github.com/herumi/ate-pairing/commit/a7d5c08225a72f0b7dd958cb7cde24337ee2933f
