### ISSUE TITLE
Why the patch file for ate-pairing

### ISSUE THREAD

**Issue by ulrichard** [scipr-lab/libsnark#36]
I would like to package libsnark for debian. But for that I need to package the dependencies as well.
Now what is the story behind  "ate-pairing-change-curve.diff" ?
Could this change be pushed to upstream so that they can include it into a new release of ate-pairing?
That would be my preferred solution anyway.

**Comment by madars** [comment]
Hi Richard! ate-pairing patch file got upstreamed with the following commit: https://github.com/herumi/ate-pairing/commit/8201a4bc82d22f9aaa375b94267aa9252cb580ef . There should no longer be ate-pairing-change-curve.diff anymore :)
