### ISSUE TITLE
Error in comment about F[p^2] implementation

### ISSUE THREAD

**Issue by daira** [scipr-lab/libsnark#46]
https://github.com/scipr-lab/libsnark/blob/master/src/algebra/fields/fp2.hpp#L27 says ``F[p^3]`` where it should say ``F[p^2]``. This is significant because I'm not sure how much to trust the rest of the comments in that file now (i.e. have they been changed from the corresponding ones in https://github.com/scipr-lab/libsnark/blob/master/src/algebra/fields/fp3.hpp ?)

**Comment by tromer** [comment]
I fixed the typo. This was indeed a copy&paste error in the boilerplate text, but I believe the substantial text, and in particular the field-specific details, are generally accurate.
