### ISSUE TITLE
random_element() segfaults

### ISSUE THREAD

**Issue by benma** [scipr-lab/libsnark#49]
```c++
#include <common/default_types/ec_pp.hpp>
int main() {
    libsnark::Fr<default_ec_pp>::random_element(); //segfault
    return 0;
```
(The Makefile I used to compile the above is here: https://github.com/benma/libsnark/blob/6be0121cbeedefc2bffd4b89e7ef268a7da90efe/link_example/Makefile)

**Comment by benma** [comment]
Nevermind, I was missing this line:
`libsnark::default_ec_pp::init_public_params();`

Sorry for the noise.

**Comment by Kyroy** [comment]
Thanks for this issue, saved me a lot of time :laughing:
