### ISSUE TITLE
Make: issue with installed headers

### ISSUE THREAD

**Issue by chfast** [scipr-lab/libsnark#68]
`make install` installs headers to `<prefix>/include/libsnark`. By convention dependent project should include `-I<prefix>/include` only. However, this does not work, because libsnark headers includes other libsnark headers without `libsnark` prefix, e.g. https://github.com/scipr-lab/libsnark/blob/master/src/algebra/curves/alt_bn128/alt_bn128_g1.hpp#L11.

**Comment by tromer** [comment]
The current convention is to `-I<prefix>/include/libsnark`.
Is there a strong reason to change that?

**Comment by chfast** [comment]
Not a very big deal. I included both paths, but will try to use only the mentioned one.
