### ISSUE TITLE
cmake-master-merging compile failed

### ISSUE THREAD

**Issue by lightning-li** [scipr-lab/libsnark#70]
<img width="1276" alt="libsnark-failed" src="https://cloud.githubusercontent.com/assets/7557388/24181641/30c4ed42-0ef7-11e7-9ede-51fdeaa8f8fb.png">

**Comment by howardwu** [comment]
Acknowledged, we will address this soon.

For now, if performance is not of critical importance, you can temporarily get around this issue by building **libff** with `cmake .. -DDEBUG=ON` and reinstalling it on your system, then building **libsnark** cmake-master-merging branch again with `cmake .. -DDEBUG=ON` and reinstalling that.

**Comment by howardwu** [comment]
Issue was resolved with dependency fixes downstream
